PACKAGE_NAME="xh2_driver"
PACKAGE_VERSION="v1.2.0"
BUILT_MODULE_NAME[0]="xh2a_drv"
DEST_MODULE_LOCATION[0]="/kernel/extra"
AUTOINSTALL="yes"
BUILD_EXCLUSIVE_KERNEL="^6\.(1|6|8|11|14|17|18)\.|^5\.(4|10|15)\.|^4\.(19)\."
